# NumPy

Official Documentation: https://numpy.org 

NumPy brings the computational power of languages like C and Fortran to Python, a language much easier to learn and use. With this power comes simplicity: a solution in NumPy is often clear and elegant.

Numpy is a numerical python tool.
Numpy == 
Numerical Python
* It is a library inside python that we Do not need to create
* USED for Scientific Computing
* IT contains n-dimentional array object

In [1]:
##Installing numpy
!pip install numpy

In [2]:
import os
import sys
import numpy as np ##We are importing numpy to use it
import time ##we use the time module to check speed

In [3]:
##Create 1 dimensionbal array in numpy
a = np.array([1,2,3])
print(a)
print(type(a)) ##CHECKING THE TYPE

[1 2 3]
<class 'numpy.ndarray'>


Creating multidimentional array

In [4]:
##creating two dimensional array
a = np.array([[1,2,3],[10,40,30]])
print (a)

[[ 1  2  3]
 [10 40 30]]


In [5]:
##creating four dimensional array
a = np.array([[1,2,3],[10,40,30],[100,90,80],[4,5,6]])
print (a)

[[  1   2   3]
 [ 10  40  30]
 [100  90  80]
 [  4   5   6]]


In [6]:
##Creating an array with all values as zero
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

So, above we used the zeros function within numpy first variable is the number of rows and then the number of columns, which is 3 in the case above.

In [7]:
##Creating arrays with regular intervals
np.arange(10) ##here starting from zero and increment by 1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2,10) ##starting point 2 specified

array([2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
##What if we want to increment by 0.1 instead of 1 and not start with 0?
np.arange(3,4,0.1)

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9])

Linspace function

In [10]:
np.linspace(1,4,6) #here we are specifying the start and end value and how many values we want among them

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

linspace is used to get values between two numbers.. 1 4 are range and 6 resprsent number of values obtained from range.
Linspace creates the arrays with specified numnber of elements and spaced equally between the specified beginning and end value 

In [11]:
np.linspace(3,3)

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

NOW LETS look at indices: indices create a set of arrays, one per dimension with variation in that dimension.

In [12]:
a = np.indices((3,3)) ##here we are creating aarray with 3 rows and 3 columns

In [13]:
a

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

Data types

In [14]:
print(a.dtype)

int64


In [15]:
a.size

18

**Difference between numpy array and list:**

Numpy array uses less memory compared to lists.
Numpy arrays are faster and more convenient than lists
Numpy array allows to easily work with numerical data


So lets verify the claims ...

In [16]:
#we use getsizeof function in the sys library to see the memory it is using
#so lets chek how much space a number takes
a = 10
print(sys.getsizeof(a)) #memory allocated to a

28


In [17]:
##So lets check memory allocation differences

list1 = range(1000) ##creating a list of 1000 values
#considering it is a list of all integers we can get size of list1 as follows:
print(sys.getsizeof(a)*len(list1))

28000


In [18]:
a1 = np.arange(1000)
print(a1.size * a1.itemsize)

8000


so see for same size numpy array is taking 8000bytes whereas list is taking 28000 bytes.

In [19]:
##Now, lests validate that numpy arrays are fast
l1 = [1,20,3]
l2 = [10,2,30]
#lets do element wise sum
x = l1+l2 ##this concats the list does not add
print('concat list result',x)
##So we need loop to perform addition
result = [(x+y) for x,y in zip(l1,l2)]
print ('addition result:',result)

concat list result [1, 20, 3, 10, 2, 30]
addition result: [11, 22, 33]


In [20]:
#Now lets try with 1000000 element containing lists
size = 1000000

list2 = range(size)
list3 = range(size)

###Now lets first instantiate timer 
start = time.time()
##Now lets add the list2 and list3 element wise
result = [(x+y) for x,y in zip(list2,list3)]
##now, lets calculate time, we will deduct start timne from current time
time_taken = time.time()- start ##time is in microseconds
print (time_taken)

0.09712457656860352


In [21]:
##Now lets do similar for numpy
n1 = np.arange(size)
n2 = np.arange(size)

##now time calculation time
start2 = time.time()
result2 = n1 + n2
time__taken =time.time()-start2
print(time__taken)


0.005153656005859375


SEE THERE IS A HUGE TIME DIFFERENCE FOR SIMILAR COMPUTATION AND WE CAN DERIVE THAT NUMPY IS FASTER.
ALSO, SEE UNLIKE IN LIST FOR DOING ELEMENT WISE ADDITION IN NUMPY WE DO NOT NEED LOOPS, BUT SIMPLE + OPERATOR DOES THE JOB!

SO WE CAN CONCLUDE NUMPY IS SUITABLE FOR BIG CALCULATIONS, THUS ITS POPULARITY FOR DATA SCIENCE.

## NUMPY OPERATIONS

In [22]:
arr = np.array([[10,20,30],[1,2,3]])
print (arr)

[[10 20 30]
 [ 1  2  3]]


lets find the dimension

In [23]:
arr.ndim

2

byte size of each element

In [24]:
arr.itemsize

8

data type of each element

In [25]:
arr.dtype

dtype('int64')

how many rows and columns in array?

In [26]:
arr.shape

(2, 3)

total number of elements in array?

In [27]:
arr.size

6

**RESHAPING an array.** 
This is a crucial function for ML.
This is basically used to reverse between rows and columns.

In [28]:
arr2 = arr
arr2.reshape(3,2)

array([[10, 20],
       [30,  1],
       [ 2,  3]])

In [45]:
np.reshape(arr2,6)

array([10, 20, 30,  1,  2,  3])

arr id s 1 D array now after reshape.

See how it got interchanged between rows and columns?

**Min and Max value within the array**

In [29]:
arr.min()

1

In [30]:
arr.max()

30

Adding all elements in the array

In [31]:
arr.sum()

66

In [32]:
##Adding along axis
np.sum(arr,axis = 0) ##summing column wise

array([11, 22, 33])

In [33]:
np.sum(arr,axis = 1) ##summing column wise

array([60,  6])

So see you can do columnwise and rowwise addition within the numpy array.

**Slicing Numpy array**

In [34]:
#Accessing a single item in arr
arr

array([[10, 20, 30],
       [ 1,  2,  3]])

In [35]:
#Say you would access 20
#you type
arr[0,1] ##here 0 is row index and 1 is column index

20

In [36]:
#TO GET CUMLTIPLE VALUES INSTEAD OF 1
arr[0:, 1] ##Here we are asking for all rows in index 1 column

array([20,  2])

In [37]:
arr[0,:2]

array([10, 20])

In [38]:
arr[0:2,1:]

array([[20, 30],
       [ 2,  3]])

So slicing can be done in rows and columns 

**MATHEMATICAL OPERATIONS**

In [39]:
print('array no. 1')
x = np.array([[1,2],[3,4]])

y = np.array([[5,6],[7,8]])

print(x)
print('array no. 2')
print(y)
print('Addition results of the two arrays')
print(x + y)



array no. 1
[[1 2]
 [3 4]]
array no. 2
[[5 6]
 [7 8]]
Addition results of the two arrays
[[ 6  8]
 [10 12]]


In [40]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

Note the add function within numpy library does the same job as the **+** operand

In [41]:
print(x - y)

[[-4 -4]
 [-4 -4]]


In [42]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [43]:
print(np.sqrt(x)) #Squareroot function

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [44]:
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
